import { access, readFile, readdir } from "node:fs/promises";
const sceneRoot="content/scenes-v3";
const sceneFiles=(await readdir(sceneRoot)).filter((file)=>file.endsWith(".json"));
const required=["README.md","package.json","content/reactions.json","public/index.html","public/app.js","public/styles.css","server/server.mjs","server/game-engine.mjs","scripts/smoke-test.mjs","docs/PROTOTYPE_V031.md",...sceneFiles.map((file)=>`${sceneRoot}/${file}`)];
for(const file of required)await access(file);
const pkg=JSON.parse(await readFile("package.json","utf8"));
const scenes=await Promise.all(sceneFiles.map(async(file)=>JSON.parse(await readFile(`${sceneRoot}/${file}`,"utf8"))));
const reactions=JSON.parse(await readFile("content/reactions.json","utf8"));
if(pkg.name!=="tomate-game"||pkg.version!=="0.3.1")throw new Error("Version attendue : tomate-game 0.3.1.");
if(!scenes.some((scene)=>scene.tutorial))throw new Error("Une scène tutoriel est obligatoire.");
if(scenes.some((scene)=>scene.cast?.length!==2||!Array.isArray(scene.lines)||scene.lines.length<7))throw new Error("Chaque histoire doit avoir deux personnages et au moins sept répliques.");
if(reactions.length<6)throw new Error("Six réactions minimum.");
console.log(`Tomate ! v0.3.1 check passed — ${scenes.length} histoires, ${scenes.reduce((sum,scene)=>sum+scene.lines.length,0)} répliques.`);
